# Generated by Django 3.1.3 on 2020-11-30 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='наименование')),
                ('image', models.ImageField(blank=True, upload_to='products_images', verbose_name='изображение')),
                ('short_description', models.CharField(max_length=120, verbose_name='краткое описание продукта')),
                ('description', models.TextField(blank=True, verbose_name='полное описание продукта')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='цена')),
                ('quantity', models.PositiveSmallIntegerField(default=0, verbose_name='количество на складе')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.productscategores', verbose_name='категория')),
            ],
        ),
    ]
