# Generated by Django 3.1.4 on 2020-12-24 10:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0008_auto_20201224_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 26, 10, 37, 8, 386432, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='shopuserprofile',
            name='photo',
            field=models.ImageField(blank=True, upload_to='', verbose_name='фото из соц_сети'),
        ),
    ]
